### ISSUE TITLE
Add container runtime and build env vars to supply chain 

### ISSUE THREAD

**Issue by bbertka-pivotal** [Tanzu-Solutions-Engineering/tanzu-to-go-workshop#8]
Would be nice to have environment variables specified in the supply chain and be able to modify these as part of the lab within workload.yaml.  This will allow attendees porting an app from another cloud native platform such as CF to quickly get an app running. For example build pack config environment variable, or user runtime container environment variables specified in workload.yaml.  

```
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  env:
    - name: CONTAINER_VAR
      value: "1234567890"
  source:
    git:
      url: https://github.com/bbertka-pivotal/tanzu-java-web-app
      ref:
        branch: main
  build:
    env:
      - name: JBP_CONFIG_OPEN_JDK_JRE 
        value: '{ jre: { version: 11.+ }, memory_calculator: { stack_threads: 25 } }'
```
